- hosts: localhost
  gather_facts: no
  vars:
    region: "us-west-2"  # Change to desired region
    account_ids:
      - "714949071610"
      - "974553378902"

  tasks:
    - name: Assume AWS role and retrieve temporary credentials
      command: >
        aws sts assume-role
        --role-arn 'arn:aws:iam::673443487762:role/TechMCrossAccountAutomation'
        --role-session-name 'test'
      register: assume_role_output

    - name: Save temporary credentials as facts
      set_fact:
        aws_access_key: "{{ assume_role_output.stdout | from_json | json_query('Credentials.AccessKeyId') }}"
        aws_secret_access_key: "{{ assume_role_output.stdout | from_json | json_query('Credentials.SecretAccessKey') }}"
        aws_session_token: "{{ assume_role_output.stdout | from_json | json_query('Credentials.SessionToken') }}"

    - name: Get Patch Report
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AWS_SESSION_TOKEN: "{{ aws_session_token }}"
      shell: |
        #!/bin/bash

        # Get the instances with SSM patch compliance data
        for account_id in "{{ account_ids }}"; do
          echo $account_id
        done
